name: ⭐ Feature Request
description: Suggest a feature to improve the JMAX STREAM app
labels: [enhancement]
body:

    - type: textarea
      id: feature-description
      attributes:
          label: Describe your suggested feature
          description: Describe the feature you had like to see added or improved.
          placeholder: |
              Example:
                "It should work like this..."
      validations:
          required: true

    - type: checkboxes
      id: acknowledgements
      attributes:
          label: Acknowledgements
          description: Read this carefully, we will close and ignore your issue if you skimmed through this.
          options:
              - label: I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
                required: true
